name: Lost Nutrition
favicon: null
layout_spectrum: 0.11260061780922115
typography_spectrum: 0.27611321001313627
title: 'Fuel your carpe diem!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#779324'
    - '#ffffff'
    - '#a4af85'
    - '#c7d3a7'
    - '#f78d27'
  brandStrength: 0.5
  lightness: 0.8093568254262209
  saturation: 0.5
  rhythmicContrast: 0.9329319470562041
purpose: []
